version: '3.1'
services:
  mongodb:
    image: 'mongo'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    expose:
            - "27017"
    volumes:
      - mongodbdata:/data/db
  pyramid:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
    ports:
      - "6543:6543"
    volumes:
      - ./livivo_sru:/livivo_sru
    depends_on:
      - mongodb

volumes:
  mongodbdata:

